server:
  http:
    addr: 0.0.0.0:8001
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 3s

data:
  gorm:
     dataSourceName: host=0.0.0.0 port=5432 user=postgres password=123456 dbname=fkratos_common sslmode=disable TimeZone=Asia/Shanghai
     maxIdleConn: 10
     maxOpenConn: 60
     connMaxLifeTime: 60s
     showLog: true
     tracing: true
  redis:
    addr: 0.0.0.0:6379
    password: "123456"
    db: 0
    dialTimeout: 1s
    readTimeout: 0.4s
    writeTimeout: 0.6s

trace:
  batcher: "jaeger"
  endpoint: "http://0.0.0.0:14268/api/traces"
  sampler: "1.0"
  env: "dev"

registry:
  type: "etcd"
  etcd:
    endpoints:
     - 0.0.0.0:2379
  polaris:
    address: 127.0.0.1
    port: 8091
    namespace: fkratos
    token: Nb+iiDm+z58f+P9wvqle5aysh7QkAtz6ELUp4oW80hlC6/zrFgFftvU056G6B9WE0D2hfY2/rrd/8KtyC9U=
  nacos:
    address: 0.0.0.0
    port: 8848
    namespaceId: "public"
    logLevel: "info"
    cacheDir: ./
    logDir: ./
    updateThreadNum: 1
    timeout: 3s
    beatInterval: 1s
    notLoadCacheAtStart: true
    updateCacheWhenEmpty: true