// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.

package fkratos_device_repo

import (
	"context"
	"encoding/json"
	"errors"
	"fkratos/app/rpc_device/internal/data/gorm/fkratos_device_dao"
	"fkratos/app/rpc_device/internal/data/gorm/fkratos_device_model"

	"github.com/fzf-labs/fpkg/orm"
	"github.com/fzf-labs/fpkg/orm/gen/cache"
	"gorm.io/gorm"
)

var _ IDeviceRepo = (*DeviceRepo)(nil)

var (
	cacheDeviceByIDPrefix = "DBCache:fkratos_device:DeviceByID"
)

type (
	IDeviceRepo interface {
		// CreateOne 创建一条数据
		CreateOne(ctx context.Context, data *fkratos_device_model.Device) error
		// CreateOneByTx 创建一条数据(事务)
		CreateOneByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error
		// UpsertOne Upsert一条数据
		UpsertOne(ctx context.Context, data *fkratos_device_model.Device) error
		// UpsertOneByTx Upsert一条数据(事务)
		UpsertOneByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error
		// CreateBatch 批量创建数据
		CreateBatch(ctx context.Context, data []*fkratos_device_model.Device, batchSize int) error
		// UpdateOne 更新一条数据
		UpdateOne(ctx context.Context, data *fkratos_device_model.Device) error
		// UpdateOne 更新一条数据(事务)
		UpdateOneByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error
		// UpdateOneWithZero 更新一条数据,包含零值
		UpdateOneWithZero(ctx context.Context, data *fkratos_device_model.Device) error
		// UpdateOneWithZero 更新一条数据,包含零值(事务)
		UpdateOneWithZeroByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error
		// FindOneCacheByID 根据ID查询一条数据并设置缓存
		FindOneCacheByID(ctx context.Context, ID string) (*fkratos_device_model.Device, error)
		// FindOneByID 根据ID查询一条数据
		FindOneByID(ctx context.Context, ID string) (*fkratos_device_model.Device, error)
		// FindMultiCacheByIDS 根据IDS查询多条数据并设置缓存
		FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*fkratos_device_model.Device, error)
		// FindMultiByIDS 根据IDS查询多条数据
		FindMultiByIDS(ctx context.Context, IDS []string) ([]*fkratos_device_model.Device, error)
		// FindMultiBySn 根据sn查询多条数据
		FindMultiBySn(ctx context.Context, sn string) ([]*fkratos_device_model.Device, error)
		// FindMultiBySns 根据sns查询多条数据
		FindMultiBySns(ctx context.Context, sns []string) ([]*fkratos_device_model.Device, error)
		// FindMultiByPaginator 查询分页数据(通用)
		FindMultiByPaginator(ctx context.Context, paginatorReq *orm.PaginatorReq) ([]*fkratos_device_model.Device, *orm.PaginatorReply, error)
		// DeleteOneCacheByID 根据ID删除一条数据并清理缓存
		DeleteOneCacheByID(ctx context.Context, ID string) error
		// DeleteOneCacheByID 根据ID删除一条数据并清理缓存
		DeleteOneCacheByIDTx(ctx context.Context, tx *fkratos_device_dao.Query, ID string) error
		// DeleteOneByID 根据ID删除一条数据
		DeleteOneByID(ctx context.Context, ID string) error
		// DeleteOneByID 根据ID删除一条数据
		DeleteOneByIDTx(ctx context.Context, tx *fkratos_device_dao.Query, ID string) error
		// DeleteMultiCacheByIDS 根据IDS删除多条数据并清理缓存
		DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiCacheByIDS 根据IDS删除多条数据并清理缓存
		DeleteMultiCacheByIDSTx(ctx context.Context, tx *fkratos_device_dao.Query, IDS []string) error
		// DeleteMultiByIDS 根据IDS删除多条数据
		DeleteMultiByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiByIDS 根据IDS删除多条数据
		DeleteMultiByIDSTx(ctx context.Context, tx *fkratos_device_dao.Query, IDS []string) error
		// DeleteUniqueIndexCache 删除唯一索引存在的缓存
		DeleteUniqueIndexCache(ctx context.Context, data []*fkratos_device_model.Device) error
	}
	DeviceRepo struct {
		db    *gorm.DB
		cache cache.IDBCache
	}
)

func NewDeviceRepo(db *gorm.DB, cache cache.IDBCache) *DeviceRepo {
	return &DeviceRepo{
		db:    db,
		cache: cache,
	}
}

// CreateOne 创建一条数据
func (d *DeviceRepo) CreateOne(ctx context.Context, data *fkratos_device_model.Device) error {
	dao := fkratos_device_dao.Use(d.db).Device
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneByTx 创建一条数据(事务)
func (d *DeviceRepo) CreateOneByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error {
	dao := tx.Device
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOne Upsert一条数据
func (d *DeviceRepo) UpsertOne(ctx context.Context, data *fkratos_device_model.Device) error {
	dao := fkratos_device_dao.Use(d.db).Device
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByTx Upsert一条数据(事务)
func (d *DeviceRepo) UpsertOneByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error {
	dao := tx.Device
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatch 批量创建数据
func (d *DeviceRepo) CreateBatch(ctx context.Context, data []*fkratos_device_model.Device, batchSize int) error {
	dao := fkratos_device_dao.Use(d.db).Device
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOne 更新一条数据
func (d *DeviceRepo) UpdateOne(ctx context.Context, data *fkratos_device_model.Device) error {
	dao := fkratos_device_dao.Use(d.db).Device
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Updates(data)
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, []*fkratos_device_model.Device{data})
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneByTx 更新一条数据(事务)
func (d *DeviceRepo) UpdateOneByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error {
	dao := tx.Device
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Updates(data)
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, []*fkratos_device_model.Device{data})
	if err != nil {
		return err
	}
	return err
}

// UpdateOneWithZero 更新一条数据,包含零值
func (d *DeviceRepo) UpdateOneWithZero(ctx context.Context, data *fkratos_device_model.Device) error {
	dao := fkratos_device_dao.Use(d.db).Device
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Select(dao.ALL.WithTable("")).Updates(data)
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, []*fkratos_device_model.Device{data})
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值
func (d *DeviceRepo) UpdateOneWithZeroByTx(ctx context.Context, tx *fkratos_device_dao.Query, data *fkratos_device_model.Device) error {
	dao := tx.Device
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Select(dao.ALL.WithTable("")).Updates(data)
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, []*fkratos_device_model.Device{data})
	if err != nil {
		return err
	}
	return err
}

// DeleteOneCacheByID 根据ID删除一条数据并清理缓存
func (d *DeviceRepo) DeleteOneCacheByID(ctx context.Context, ID string) error {
	dao := fkratos_device_dao.Use(d.db).Device
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, []*fkratos_device_model.Device{result})
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByID 根据ID删除一条数据并清理缓存
func (d *DeviceRepo) DeleteOneCacheByIDTx(ctx context.Context, tx *fkratos_device_dao.Query, ID string) error {
	dao := tx.Device
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, []*fkratos_device_model.Device{result})
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByID 根据ID删除一条数据
func (d *DeviceRepo) DeleteOneByID(ctx context.Context, ID string) error {
	dao := fkratos_device_dao.Use(d.db).Device
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByID 根据ID删除一条数据
func (d *DeviceRepo) DeleteOneByIDTx(ctx context.Context, tx *fkratos_device_dao.Query, ID string) error {
	dao := tx.Device
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDS 根据IDS删除多条数据并清理缓存
func (d *DeviceRepo) DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error {
	dao := fkratos_device_dao.Use(d.db).Device
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDS 根据IDS删除多条数据并清理缓存
func (d *DeviceRepo) DeleteMultiCacheByIDSTx(ctx context.Context, tx *fkratos_device_dao.Query, IDS []string) error {
	dao := tx.Device
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteUniqueIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDS 根据IDS删除多条数据
func (d *DeviceRepo) DeleteMultiByIDS(ctx context.Context, IDS []string) error {
	dao := fkratos_device_dao.Use(d.db).Device
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDS 根据IDS删除多条数据
func (d *DeviceRepo) DeleteMultiByIDSTx(ctx context.Context, tx *fkratos_device_dao.Query, IDS []string) error {
	dao := tx.Device
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteUniqueIndexCache 删除唯一索引存在的缓存
func (d *DeviceRepo) DeleteUniqueIndexCache(ctx context.Context, data []*fkratos_device_model.Device) error {
	keys := make([]string, 0)
	for _, v := range data {
		keys = append(keys, d.cache.Key(cacheDeviceByIDPrefix, v.ID))

	}
	err := d.cache.DelBatch(ctx, keys)
	if err != nil {
		return err
	}
	return nil
}

// FindOneCacheByID 根据ID查询一条数据并设置缓存
func (d *DeviceRepo) FindOneCacheByID(ctx context.Context, ID string) (*fkratos_device_model.Device, error) {
	resp := new(fkratos_device_model.Device)
	cacheKey := d.cache.Key(cacheDeviceByIDPrefix, ID)
	cacheValue, err := d.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := fkratos_device_dao.Use(d.db).Device
		result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := json.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	})
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal([]byte(cacheValue), resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// FindOneByID 根据ID查询一条数据
func (d *DeviceRepo) FindOneByID(ctx context.Context, ID string) (*fkratos_device_model.Device, error) {
	dao := fkratos_device_dao.Use(d.db).Device
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByIDS 根据IDS查询多条数据并设置缓存
func (d *DeviceRepo) FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*fkratos_device_model.Device, error) {
	resp := make([]*fkratos_device_model.Device, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, v := range IDS {
		cacheKey := d.cache.Key(cacheDeviceByIDPrefix, v)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = v
	}
	cacheValue, err := d.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		parameters := make([]string, 0)
		for _, v := range miss {
			parameters = append(parameters, keyToParam[v])
		}
		dao := fkratos_device_dao.Use(d.db).Device
		result, err := dao.WithContext(ctx).Where(dao.ID.In(parameters...)).Find()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, err
		}
		value := make(map[string]string)
		for _, v := range miss {
			value[v] = ""
		}
		for _, v := range result {
			marshal, err := json.Marshal(v)
			if err != nil {
				return nil, err
			}
			value[d.cache.Key(cacheDeviceByIDPrefix, v.ID)] = string(marshal)
		}
		return value, nil
	})
	if err != nil {
		return nil, err
	}
	for _, v := range cacheValue {
		tmp := new(fkratos_device_model.Device)
		err := json.Unmarshal([]byte(v), tmp)
		if err != nil {
			return nil, err
		}
		resp = append(resp, tmp)
	}
	return resp, nil
}

// FindMultiByIDS 根据IDS查询多条数据
func (d *DeviceRepo) FindMultiByIDS(ctx context.Context, IDS []string) ([]*fkratos_device_model.Device, error) {
	dao := fkratos_device_dao.Use(d.db).Device
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiBySn 根据sn查询多条数据
func (d *DeviceRepo) FindMultiBySn(ctx context.Context, sn string) ([]*fkratos_device_model.Device, error) {
	dao := fkratos_device_dao.Use(d.db).Device
	result, err := dao.WithContext(ctx).Where(dao.Sn.Eq(sn)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiBySns 根据sns查询多条数据
func (d *DeviceRepo) FindMultiBySns(ctx context.Context, sns []string) ([]*fkratos_device_model.Device, error) {
	dao := fkratos_device_dao.Use(d.db).Device
	result, err := dao.WithContext(ctx).Where(dao.Sn.In(sns...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiByPaginator 查询分页数据(通用)
func (d *DeviceRepo) FindMultiByPaginator(ctx context.Context, paginatorReq *orm.PaginatorReq) ([]*fkratos_device_model.Device, *orm.PaginatorReply, error) {
	result := make([]*fkratos_device_model.Device, 0)
	var total int64
	whereExpressions, orderExpressions, err := paginatorReq.ConvertToGormExpression(fkratos_device_model.Device{})
	if err != nil {
		return result, nil, err
	}
	err = d.db.WithContext(ctx).Model(&fkratos_device_model.Device{}).Select([]string{"*"}).Clauses(whereExpressions...).Count(&total).Error
	if err != nil {
		return result, nil, err
	}
	if total == 0 {
		return result, nil, nil
	}
	paginatorReply := paginatorReq.ConvertToPage(int(total))
	err = d.db.WithContext(ctx).Model(&fkratos_device_model.Device{}).Limit(paginatorReply.Limit).Offset(paginatorReply.Offset).Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
	if err != nil {
		return result, nil, err
	}
	return result, paginatorReply, err
}
