// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fkratos_user_model

import (
	"database/sql"

	"gorm.io/gorm"
)

const TableNameUserRule = "user_rule"

// UserRule mapped from table <user_rule>
type UserRule struct {
	ID        string         `gorm:"column:id;primaryKey;default:gen_random_uuid();comment:ID" json:"id"`                                                       // ID
	Pid       string         `gorm:"column:pid;not null;comment:上级菜单" json:"pid"`                                                                               // 上级菜单
	Type      string         `gorm:"column:type;not null;comment:类型:route=路由,menu_dir=菜单目录,menu=菜单项,nav_user_menu=顶栏会员菜单下拉项,nav=顶栏菜单项,button=页面按钮" json:"type"` // 类型:route=路由,menu_dir=菜单目录,menu=菜单项,nav_user_menu=顶栏会员菜单下拉项,nav=顶栏菜单项,button=页面按钮
	Title     string         `gorm:"column:title;not null;comment:标题" json:"title"`                                                                             // 标题
	Name      string         `gorm:"column:name;not null;comment:规则名称" json:"name"`                                                                             // 规则名称
	Path      string         `gorm:"column:path;not null;comment:路由路径" json:"path"`                                                                             // 路由路径
	Icon      string         `gorm:"column:icon;not null;comment:图标" json:"icon"`                                                                               // 图标
	MenuType  string         `gorm:"column:menu_type;not null;comment:菜单类型:tab=选项卡,link=链接,iframe=Iframe" json:"menuType"`                                      // 菜单类型:tab=选项卡,link=链接,iframe=Iframe
	URL       string         `gorm:"column:url;not null;comment:URL" json:"url"`                                                                                // URL
	Component string         `gorm:"column:component;not null;comment:组件路径" json:"component"`                                                                   // 组件路径
	Extend    string         `gorm:"column:extend;not null;comment:扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单" json:"extend"`                       // 扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单
	Remark    string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                                                                           // 备注
	Status    int16          `gorm:"column:status;not null;comment:状态" json:"status"`                                                                           // 状态
	CreatedAt sql.NullTime   `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                                           // 创建时间
	UpdatedAt sql.NullTime   `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                                                           // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deletedAt"`                                                                           // 删除时间
}

// TableName UserRule's table name
func (*UserRule) TableName() string {
	return TableNameUserRule
}
