name: bff_api
server:
  http:
    addr: 0.0.0.0:8801
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9901
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=localhost port=5432 user=postgres password=123456 dbname=fkratos_user sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: host.docker.internal:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
trace:
  batcher: "otlphttp"
  endpoint: "0.0.0.0:55681"
  insecure: true
  sampler: "1.0"
  env: "dev"

registry:
  type: "etcd"
  etcd:
    endpoints:
      - 0.0.0.0:2379
  nacos:
    address: 0.0.0.0
    port: 8848
    namespaceId: "public"
    logLevel: "info"
    cacheDir: ./
    logDir: ./
    updateThreadNum: 1
    timeout: 5s
    beatInterval: 1s
    notLoadCacheAtStart: false
    updateCacheWhenEmpty: true
apiDoc:
  apiFox:
    accessToken: APS-1zB0KpDZlq5eunxay3GzoRYC6AdeuXg9
    projectId: "3366291"