// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package rpc_sys_model

import "database/sql"

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID            string       `gorm:"column:id;primaryKey;comment:编号" json:"id"`
	TenantID      string       `gorm:"column:tenant_id;comment:租户ID" json:"tenantId"`
	Pid           string       `gorm:"column:pid;not null;comment:父级id" json:"pid"`
	Name          string       `gorm:"column:name;not null;comment:名称" json:"name"`
	PermissionIds string       `gorm:"column:permission_ids;comment:菜单权限集合" json:"permissionIds"`
	Remark        string       `gorm:"column:remark;comment:备注" json:"remark"`
	Status        int16        `gorm:"column:status;not null;comment:0=禁用 1=开启" json:"status"`
	Sort          int64        `gorm:"column:sort;not null;comment:排序值" json:"sort"`
	CreatedAt     sql.NullTime `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt     sql.NullTime `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt     sql.NullTime `gorm:"column:deleted_at;comment:删除时间" json:"deletedAt"`
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
