// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package rpc_sys_model

import "database/sql"

const TableNameSysPermission = "sys_permission"

// SysPermission mapped from table <sys_permission>
type SysPermission struct {
	ID        string       `gorm:"column:id;primaryKey" json:"id"`
	TenantID  string       `gorm:"column:tenant_id;comment:租户ID" json:"tenantId"`
	Pid       string       `gorm:"column:pid;not null;comment:上级菜单" json:"pid"`
	Type      string       `gorm:"column:type;not null;comment:类型:menu_dir=菜单目录,menu=菜单项,button=页面按钮" json:"type"`
	Title     string       `gorm:"column:title;not null;comment:标题" json:"title"`
	Name      string       `gorm:"column:name;not null;comment:规则名称" json:"name"`
	Path      string       `gorm:"column:path;not null;comment:路由路径" json:"path"`
	Icon      string       `gorm:"column:icon;not null;comment:图标" json:"icon"`
	MenuType  string       `gorm:"column:menu_type;comment:菜单类型:tab=选项卡,link=链接,iframe=Iframe" json:"menuType"`
	URL       string       `gorm:"column:url;not null;comment:Url" json:"url"`
	Component string       `gorm:"column:component;not null;comment:组件路径" json:"component"`
	Extend    string       `gorm:"column:extend;not null;comment:扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单" json:"extend"`
	Remark    string       `gorm:"column:remark;not null;comment:备注" json:"remark"`
	Sort      int64        `gorm:"column:sort;not null;comment:权重(排序)" json:"sort"`
	Status    int16        `gorm:"column:status;not null;comment:0=禁用 1=开启" json:"status"`
	CreatedAt sql.NullTime `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt sql.NullTime `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt sql.NullTime `gorm:"column:deleted_at;comment:删除时间" json:"deletedAt"`
}

// TableName SysPermission's table name
func (*SysPermission) TableName() string {
	return TableNameSysPermission
}
