server:
  http:
    addr: 0.0.0.0:8802
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9902
    timeout: 3s
data:
  database:
    driver: postgres
    source: host=localhost port=5432 user=postgres password=123456 dbname=fkratos_user sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: 0.0.0.0:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
trace:
  batcher: "jaeger"
  endpoint: "http://0.0.0.0:14268/api/traces"
  sampler: "1.0"
  env: "dev"

registry:
  type: "polaris"
  polaris:
    address: 127.0.0.1
    port: 8091
    instanceCount: 1
    namespace: fkratos
    service: bff_admin
    token: nu/0WRA4EqSR1FagrjRj0fZwPXuGlMpX+zCuWu4uMqy8xr1vRjisSbA25aAC3mtU8MeeRsKhQiDAynUR09I=