server:
  http:
    addr: 0.0.0.0:8001
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 3s

data:
  gorm:
     dataSourceName: host=0.0.0.0 port=5432 user=postgres password=123456 dbname=fkratos_user sslmode=disable TimeZone=Asia/Shanghai
     maxIdleConn: 10
     maxOpenConn: 60
     connMaxLifeTime: 60s
     showLog: true
     tracing: true
  redis:
    addr: 0.0.0.0:6379
    password: "123456"
    db: 0
    dialTimeout: 1s
    readTimeout: 0.4s
    writeTimeout: 0.6s

trace:
  batcher: "jaeger"
  endpoint: "http://0.0.0.0:14268/api/traces"
  sampler: "1.0"
  env: "dev"

registry:
  type: "etcd"
  etcd:
    endpoints:
     - 0.0.0.0:2379
  polaris:
    address: 127.0.0.1
    port: 8091
    namespace: fkratos
    service: rpc.user
    token: nu/0WRA4EqSR1FagrjRj0fZwPXuGlMpX+zCuWu4uMqy8xr1vRjisSbA25aAC3mtU8MeeRsKhQiDAynUR09I=