// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fkratos/app/rpc_sys/internal/biz"
	"fkratos/app/rpc_sys/internal/data"
	"fkratos/app/rpc_sys/internal/server"
	"fkratos/app/rpc_sys/internal/service"
	"fkratos/internal/bootstrap"
	"fkratos/internal/bootstrap/conf"
	"github.com/fzf-labs/fpkg/cache/rockscache"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confBootstrap *conf.Bootstrap, logger log.Logger, registrar registry.Registrar, discovery registry.Discovery) (*kratos.App, func(), error) {
	db := bootstrap.NewGorm(confBootstrap, logger)
	client := bootstrap.NewRedis(confBootstrap, logger)
	rockscacheClient := rockscache.NewWeakRocksCacheClient(client)
	asynqClient := bootstrap.NewAysnqClient(confBootstrap)
	dataData, cleanup, err := data.NewData(confBootstrap, logger, db, client, rockscacheClient, asynqClient)
	if err != nil {
		return nil, nil, err
	}
	sysAdminRepo := data.NewSysAdminRepo(confBootstrap, dataData, logger)
	authUseCase := biz.NewAuthUseCase(logger, sysAdminRepo)
	authService := service.NewAuthService(logger, authUseCase)
	sysRoleRepo := data.NewSysRoleRepo(dataData, logger)
	sysJobRepo := data.NewSysJobRepo(dataData, logger)
	sysDeptRepo := data.NewSysDeptRepo(dataData, logger)
	sysPermissionRepo := data.NewSysPermissionRepo(dataData, logger)
	adminUseCase := biz.NewAdminUseCase(logger, client, rockscacheClient, sysAdminRepo, sysRoleRepo, sysJobRepo, sysDeptRepo, sysPermissionRepo)
	adminService := service.NewAdminService(logger, adminUseCase)
	roleUseCase := biz.NewRoleUseCase(logger, sysRoleRepo)
	roleService := service.NewRoleService(logger, roleUseCase)
	permissionUseCase := biz.NewPermissionUseCase(logger, sysPermissionRepo)
	permissionService := service.NewPermissionService(logger, permissionUseCase)
	jobUseCase := biz.NewJobUseCase(logger, sysJobRepo)
	jobService := service.NewJobService(logger, jobUseCase)
	deptUseCase := biz.NewDeptUseCase(logger, sysDeptRepo)
	deptService := service.NewDeptService(logger, deptUseCase)
	sysAPIRepo := data.NewSysAPIRepo(dataData, logger)
	apiUseCase := biz.NewAPIUseCase(logger, sysAPIRepo)
	apiService := service.NewAPIService(logger, apiUseCase)
	sysLogRepo := data.NewSysLogRepo(dataData, logger)
	logUseCase := biz.NewLogUseCase(logger, sysLogRepo, sysAdminRepo, sysAPIRepo)
	logService := service.NewLogService(logger, logUseCase)
	dashboardService := service.NewDashboardService(logger)
	grpcServer := server.NewGRPCServer(confBootstrap, logger, authService, adminService, roleService, permissionService, jobService, deptService, apiService, logService, dashboardService)
	app := newApp(logger, registrar, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
